---
- name: Deploy MongoDB MMS Automation Agent
  hosts: all
  become: yes
  vars:
    artifactory_url: "{{ mms_agent_url }}"
    install_dir: /opt/mongodb/mongodb-mms-automation-agent
    binary_name: mongodb-mms-automation-agent
    service_file: mongodb-mms-automation-agent.service

  tasks:
    - name: Create mongodb group
      ansible.builtin.group:
        name: mongodb
        state: present
        system: yes

    - name: Create mongodb user
      ansible.builtin.user:
        name: mongodb
        group: mongodb
        state: present
        system: yes
        shell: /bin/false
        home: /opt/mongodb
        create_home: no

    - name: Create installation directory
      ansible.builtin.file:
        path: "{{ install_dir }}"
        state: directory
        owner: mongodb
        group: mongodb
        mode: '0755'

    - name: Download MMS Automation Agent binary from Artifactory
      ansible.builtin.get_url:
        url: "{{ mms_agent_url }}"
        dest: "{{ install_dir }}/{{ binary_name }}"
        owner: mongodb
        group: mongodb
        mode: '0755'

    - name: Create local.config for MMS Automation Agent
      ansible.builtin.copy:
        dest: "{{ install_dir }}/local.config"
        owner: mongodb
        group: mongodb
        mode: '0644'
        content: |
          mmsGroupId=<Insert Group IP Here>
          mmsApiKey=<Insert Agent API Key Here>
          mmsBaseUrl=https://mopsmgr-stage-db.test.mastercard-uscentral.sep:8443
          logFile=/data/mongodb/logs/automation-agent.log

    - name: Create symbolic link to mms agent binary
      ansible.builtin.file:
        src: /opt/mongodb/mongodb-mms-automation-agent-108.0.13.8870-1.rhel8_x86_64/mongodb-linux-x86_64-enterprise-rhel88-8.2.0
        dest: /opt/mongodb/product
        state: link
        force: yes

    - name: Copy systemd service file
      ansible.builtin.copy:
        src: "{{ binary_name }}.service"
        dest: /usr/lib/systemd/system/{{ service_file }}
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start and enable MongoDB MMS Automation Agent service
      ansible.builtin.systemd:
        name: "{{ service_file }}"
        state: started
        enabled: yes